### ISSUE TITLE
Lost Entities

### ISSUE THREAD

**Issue by grulibre** [cibernox/homeassistant-poolstation#12]
Hello, First i want to thank you this great job, to be able to control my pool with home assistant for me is great. Since last update (AUGUST 2023) I lost a lot of entities like PH, ORP, salt concentration, temperature. I can only see 4 Relays and 4 Digital inputs. You know why?

**Comment by cibernox** [comment]
That's weird. There was a bug in an earlier version of this addon that messed the entity names, but it was fixed within a day. Are you both sure you are on the latest code? I do have all the sensors available.

**Comment by grulibre** [comment]
This is what it says, since last update:

Logger: homeassistant.loader
Source: custom_components/poolstation/sensor.py:45
Integration: Poolstation ([documentation](https://github.com/cibernox/homeassistant-poolstation), [issues](https://github.com/cibernox/homeassistant-poolstation/issues))
First occurred: 11:38:22 (1 occurrences)
Last logged: 11:38:22

Unexpected exception importing platform custom_components.poolstation.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/poolstation/sensor.py", line 45, in <module>
    device_class=SensorDeviceClass.PH,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PH

___________

Logger: homeassistant.setup
Source: setup.py:344
First occurred: 11:38:22 (2 occurrences)
Last logged: 11:38:22

Unable to prepare setup for platform poolstation.sensor: Platform not found (Exception importing custom_components.poolstation.sensor).
Unable to prepare setup for platform poolstation.number: Platform not found (Exception importing custom_components.poolstation.number).

**Comment by cibernox** [comment]
In that case I believe that the reason is that you have an outdated version of home assistant. A new kind of device class for PH sensors has introduced in 2023.08 (I added it to home assistant), and this integration started using a couple weeks after.

**Comment by luigixx73** [comment]
I am running 2023.5.3 but don't want to upgrade because other integrations stop working.
Is this possible to install prior versions of your integration ?
It always offers me to download 1ca2ce3

**Comment by cibernox** [comment]
Probably, but first met me check if it’s possible to conditionally use this new feature only if present.

**Comment by luigixx73** [comment]
It will be great to preserve backward compatibility.

**Comment by grulibre** [comment]
> In that case I believe that the reason is that you have an outdated version of home assistant. A new kind of device class for PH sensors has introduced in 2023.08 (I added it to home assistant), and this integration started using a couple weeks after.

That was right, I updated my home assistant and it works fine.!!! Thanks

**Comment by cibernox** [comment]
@luigixx73 I released a new version that **I think** will allow the integration to work in versions older than 2023.08, but since I'm in that version I couldn't verify that it works myself. Give it a try.

**Comment by luigixx73** [comment]
Hi @cibernox, it is beautifully working now with 2023.5.3
All entities added successfully.
Thanks for the prompt fix!

**Comment by cibernox** [comment]
Great, i'll close this then.
