### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by egtltd** [cibernox/homeassistant-poolstation#24]
Hello, I have 
Home Assistant 
Core 2024.9.1
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240906.0

And when try to install Poolstation i take this message:
Please wait, starting configuration wizard for Poolstation

and then take this message:
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

At log find this:
Log details (ERROR)
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 8:35:15 PM (3 occurrences)
Last logged: 8:35:29 PM

Unable to install package pypoolstation==0.5.5: ERROR: Could not find a version that satisfies the requirement pypoolstation==0.5.5 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.1, 0.5.2, 0.5.3, 0.5.4) ERROR: No matching distribution found for pypoolstation==0.5.5

Please can help me.

**Comment by cibernox** [comment]
@egtltd we introduced this error 2 days ago. I believe I've just fixed it. Please try again.

**Comment by cibernox** [comment]
Closing.Please reopen if this is still an issue
