### ISSUE TITLE
integration problem

### ISSUE THREAD

**Issue by pjlet** [cibernox/homeassistant-poolstation#3]
hi cibernox

i have installed poolstation integration ans after i entered my email ans password i have this message in the integration card : 

Réessayer la configuration: could not convert string to float: '-----'

have you an idee to solve the problem ? 

thanks for your help

**Comment by arturonaredo** [comment]
Hi @pjlet, 

this issue affects to PyPoolstation code and is already open: https://github.com/cibernox/PyPoolstation/issues/2 

Best

**Comment by pjlet** [comment]
this is resolved with the update of the python

thanks so lot
